
CREATE OR REPLACE PACKAGE PAQ1
AS 
    TYPE C_VARIABLE IS REF CURSOR;
    FUNCTION DEVOLVER_DATOS(C1 IN OUT C_VARIABLE,X NUMBER)RETURN VARCHAR2;
    END;
/

/* Siempre que se mandae un objeto de tipo cursor 
se manda de tipo in out unidos o sale error*/
CREATE OR REPLACE PACKAGE BODY PAQ1 AS

    FUNCTION DEVOLVER_DATOS(C1 IN OUT C_VARIABLE, X NUMBER)RETURN VARCHAR2
    IS
    
    DEPART DEPARTMENTS%ROWTYPE;
    EMPL EMPLOYEES%ROWTYPE;
    
      BEGIN 
        IF X=1 THEN 
        OPEN C1 FOR SELECT * FROM employees;
        FETCH C1 INTO EMPL;
        RETURN EMPL.FIRST_NAME;
    
         ELSE
         OPEN C1 FOR SELECT * FROM DEPARTMENTS;
        FETCH C1 INTO DEPART;
        RETURN DEPART.DEPARTMENT_NAME;
    
         END IF;
    END;
END;
/

SET SERVEROUTPUT ON 
DECLARE 

    DATOS PAQ1.C_VARIABLE;

BEGIN 
DBMS_OUTPUT.PUT_LINE(PAQ1.DEVOLVER_DATOS(DATOS,1));
DBMS_OUTPUT.PUT_LINE(PAQ1.DEVOLVER_DATOS(DATOS,2));
END;
/
    